version: 2.1
orbs:
  android: circleci/android@1.0.3
  codecov: codecov/codecov@3.0.0
jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Lint & Unit tests
          command: ./gradlew lint jacocoTestReport
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - codecov/upload:
          file: app/build/coverage-report
      - run:
          name: Assemble build release
          command: ./gradlew assembleRelease

workflows:
  myworkflow:
    jobs:
      - build
